# Generated by Django 3.2.8 on 2021-11-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("joueur", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnages",
            name="sex",
            field=models.CharField(
                choices=[("M", "mâle"), ("F", "femelle")],
                max_length=50,
                verbose_name="sexe",
            ),
        ),
    ]
