version: "3.1"

services:

  db:
    build: ./database
    container_name: "database"
    restart: "no"
    ports: 
      - "5532:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: docker
#      POSTGRES_DB: postgres
    networks:
      db_network:
        ipv4_address: 172.21.0.2 

  pytest:
    build: ./jenkins_ci
    container_name: "pytest"
    restart: "no"
    ports:
      - "8280:8080"
    networks:
      db_network:
        ipv4_address: 172.21.0.3
    depends_on:
      - "db"
    command: tail -f /dev/null

  adminer:
    image: adminer
    restart: always
    ports:
      - "8180:8080"

networks:
  db_network:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
