version: '3.1'

services:

  db:
    build: ./database
    container_name: database
    restart: always
    ports: 
      - 5532:5432
    environment:
      POSTGRES_USER: olivierx
      POSTGRES_PASSWORD: XXXX
      POSTGRES_DATABASE: perso
    networks:
      - pytest_network

  pytest:
    build: ./jenkins_ci
    container_name: pytest
    restart: always
    ports:
      - 8280:8080
    networks:
      - pytest_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8180:8080

networks:
  pytest_network:

volumes:
