version: '3'

services:
  db-host:
    build:
      context: postgres_build
    container_name: db-host
    restart: always
    volumes:
      - ./postgres_build/db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  jenkins:
    depends_on:
      - db-host
    build:
      context: caverne_jenkins_build
    container_name: my-jenkins
    ports:
      - 8086:8080
      - 50000:50000
    restart: always
    volumes:
      - /home/Olivier-N/jenkins_caverne:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  caverne:
    depends_on:
      - db-host
    build:
      context: ../la_caverne
      dockerfile: caverne_build/Dockerfile
    container_name: la_caverne
    command: bash -c "sudo service nginx start && python3 manage.py runserver"
    ports:
      - 8000:8000
      - 80:80
    restart: always


volumes:
  db_data: {}